### ISSUE TITLE
I have a question.

### ISSUE THREAD

**Issue by ousi-fk** [AHaumer/EMOTH#1]
Thank you for your response the other day.
I tried as you instructed and was able to change the driving cycle.

However, when I tried to run Examples.TestWithDriver, I got the following three outputs.

[1] Script Notification
EMOTH requested package VehicleInterfaces of version 2.0.0. VehicleInterfaces 2.0.1 is used instead which states that it is fully compatible without Conversion Error Notification EMOTH requested package VehicleInterfaces of version 2.0.0.

[2] Conversion Error
[SingleTrackData: 10:3-12:99]: Type mismatch in modifier of component track.inclusionDatatable, declared type Real[:::], got modifier {} of type #T_UNKNOWN#[0].

[3] Conversion Error
Error occurred while flattening model EMOTH.

[1] The Script Notification indicated that it was a problem with the version of VehicleInterfaces, but since it was indicated as compatible, I interpreted it as not being a problem.
[2] Conversion Error stated "parameter Real table[:, :] = fill(0.0, 0, 2)" in the text view.
Also, I was told that I could retry code generation with the old frontend, so I retried with Tools->Options->Simulation->Enable old frontend for code generation, but the output was as follows.
[2] Conversion Error
[SingleTrackData: 10:3-12:99]: Variable fill[0.0,2] not found in scope EMOTH.

I have tried re-downloading, etc., but no improvement, so can you please tell me how to make the change?

**Comment by AHaumer** [comment]
I also have troubles compiling this example with OM -> reported to OpenModelica
